create table if not exists trips (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date date not null,
  customer text not null default '',
  from_place text not null default '',
  to_place text not null default '',
  km numeric not null default 0,
  revenue numeric not null default 0,
  costs jsonb not null default '{}'::jsonb,
  cost numeric not null default 0,
  profit numeric not null default 0,
  trip_count integer not null default 1
);

-- Nếu bảng trips đã tồn tại từ trước, chạy thêm dòng dưới đây trong Neon SQL Editor
-- để thêm cột "Số chuyến thực tế" (mặc định 1 cho các dòng đã có sẵn):
alter table trips add column if not exists trip_count integer not null default 1;
