create table if not exists trips (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date date not null,
  customer text not null default '',
  from_place text not null default '',
  to_place text not null default '',
  km numeric not null default 0,
  revenue numeric not null default 0,
  costs jsonb not null default '{}'::jsonb,
  cost numeric not null default 0,
  profit numeric not null default 0
);
