 "use client";
import {useEffect,useMemo,useState} from "react";

const money=n=>new Intl.NumberFormat("vi-VN").format(Math.round(Number(n)||0))+"đ";
const today=new Date().toISOString().slice(0,10);
function totals(a){return {rev:a.reduce((s,x)=>s+Number(x.revenue||0),0),cost:a.reduce((s,x)=>s+Number(x.cost||0),0),profit:a.reduce((s,x)=>s+Number(x.profit||0),0),n:a.length}}
function dateVN(d){return new Date(d+"T00:00:00").toLocaleDateString("vi-VN")}

export default function Dashboard(){
 const [trips,setTrips]=useState([]),[view,setView]=useState("dash"),[edit,setEdit]=useState(null),[month,setMonth]=useState(today.slice(0,7)),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch("/api/trips");if(r.ok)setTrips(await r.json());setLoading(false)}
 useEffect(()=>{load()},[]);
 async function logout(){await fetch("/api/auth",{method:"DELETE"});location.href="/login"}
 const months=[...new Set(trips.map(x=>x.date.slice(0,7)))].sort().reverse();
 const monthTrips=trips.filter(x=>x.date.startsWith(month)); const t=totals(monthTrips);
 function openAdd(){setEdit({date:today,customer:"",from:"",to:"",km:"",revenue:"",costs:{fuel:"",driver:"",road:"",loading:"",other:""}});setView("form")}
 function card(x){return <div className="trip" key={x.id} onClick={()=>{setEdit({...x,from:x.from_place,to:x.to_place});setView("form")}}><div className="triptop"><span className="muted">{dateVN(x.date)}</span><span className="pill">Hoàn thành</span></div><h3>{x.from_place||"—"} → {x.to_place||"—"}</h3><div className="muted">{x.customer||"Khách lẻ"} · {x.km||0} km</div><div className="tripbottom" style={{marginTop:10}}><span>Thu <b className="green">{money(x.revenue)}</b></span><span>Chi <b className="red">{money(x.cost)}</b></span><span>Lời <b className="green">{money(x.profit)}</b></span></div></div>}
 return <div className="app"><header className="top"><h1>{view==="dash"?"Tổng quan":view==="trips"?"Chuyến xe":view==="report"?"Báo cáo":"Thêm chuyến"}</h1><button className="logout" onClick={logout}>Thoát</button></header><main className="content">
 {loading?<div className="empty">Đang tải dữ liệu...</div>:view==="dash"?<><div className="hero"><div>Tháng {month.slice(5,7)}/{month.slice(0,4)}</div><div className="big">{money(t.profit)}</div><div>Lợi nhuận · {t.n} chuyến</div></div><div className="grid"><div className="card stat"><span>Doanh thu</span><b className="green">{money(t.rev)}</b></div><div className="card stat"><span>Chi phí</span><b className="red">{money(t.cost)}</b></div><div className="card stat"><span>Lợi nhuận</span><b className="green">{money(t.profit)}</b></div><div className="card stat"><span>Số chuyến</span><b>{t.n}</b></div></div><div className="section">Tổng quan tháng</div><div className="card"><div className="summary"><span>Biên lợi nhuận</span><b>{t.rev?(t.profit/t.rev*100).toFixed(1):0}%</b></div><div className="summary"><span>Lợi nhuận/chuyến</span><b className="green">{money(t.n?t.profit/t.n:0)}</b></div></div><div className="section">Chuyến gần nhất</div>{monthTrips.slice(0,3).map(card)}</>:view==="trips"?<><div className="toolbar"><select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Tất cả tháng</option>{months.map(m=><option key={m}>{m}</option>)}</select></div>{trips.filter(x=>!month||x.date.startsWith(month)).map(card)}</>:view==="report"?<><div className="toolbar"><select value={month} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m}>{m}</option>)}</select></div><div className="hero"><div>LỢI NHUẬN THÁNG</div><div className="big">{money(t.profit)}</div><div>{t.n} chuyến · Biên lợi nhuận {t.rev?(t.profit/t.rev*100).toFixed(1):0}%</div></div><div className="card"><div className="summary"><span>Doanh thu</span><b className="green">{money(t.rev)}</b></div><div className="summary"><span>Chi phí</span><b className="red">{money(t.cost)}</b></div><div className="summary"><span>Lợi nhuận</span><b className="green">{money(t.profit)}</b></div></div><div className="section">Các chuyến trong tháng</div>{monthTrips.map(card)}</>:<TripForm initial={edit} onSaved={()=>{setView("trips");load()}} onCancel={()=>setView("dash")}/>}
 </main><nav className="nav"><button className={view==="dash"?"active":""} onClick={()=>setView("dash")}>⌂<br/>Tổng quan</button><button className={view==="trips"?"active":""} onClick={()=>setView("trips")}>▣<br/>Chuyến xe</button><button className="fab" onClick={openAdd}>+</button><button className={view==="report"?"active":""} onClick={()=>setView("report")}>▥<br/>Báo cáo</button></nav></div>
}

function TripForm({initial,onSaved,onCancel}){
 const [x,setX]=useState(initial); const [saving,setSaving]=useState(false);
 useEffect(()=>setX(initial),[initial]);
 function set(k,v){setX(a=>({...a,[k]:v}))}
 function setc(k,v){setX(a=>({...a,costs:{...a.costs,[k]:v}}))}
 const cost=Object.values(x?.costs||{}).reduce((s,v)=>s+(Number(v)||0),0), profit=(Number(x?.revenue)||0)-cost;
 async function save(){setSaving(true);const body={date:x.date,customer:x.customer,from:x.from,to:x.to,km:Number(x.km)||0,revenue:Number(x.revenue)||0,costs:x.costs,cost,profit};const r=await fetch(x.id?`/api/trips?id=${x.id}`:"/api/trips",{method:x.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setSaving(false);if(!r.ok){alert("Không lưu được dữ liệu");return}onSaved()}
 async function del(){if(!confirm("Xóa chuyến này?"))return;await fetch(`/api/trips?id=${x.id}`,{method:"DELETE"});onSaved()}
 return <><div className="form"><div className="section" style={{marginTop:0}}>Thông tin chuyến</div><div className="field"><label>Ngày chạy</label><input type="date" value={x.date||today} onChange={e=>set("date",e.target.value)}/></div><div className="field"><label>Khách hàng</label><input value={x.customer||""} onChange={e=>set("customer",e.target.value)} placeholder="Công ty ABC"/></div><div className="row"><div className="field"><label>Điểm đi</label><input value={x.from||""} onChange={e=>set("from",e.target.value)} placeholder="TP.HCM"/></div><div className="field"><label>Điểm đến</label><input value={x.to||""} onChange={e=>set("to",e.target.value)} placeholder="Bình Dương"/></div></div><div className="field"><label>Số km</label><input type="number" value={x.km||""} onChange={e=>set("km",e.target.value)}/></div></div><div className="form"><div className="section" style={{marginTop:0}}>Doanh thu</div><div className="field"><label>Tiền cước</label><input type="number" value={x.revenue||""} onChange={e=>set("revenue",e.target.value)}/></div></div><div className="form"><div className="section" style={{marginTop:0}}>Chi phí</div>{[["fuel","Dầu"],["driver","Tài xế"],["road","Cầu đường"],["loading","Bốc xếp"],["other","Chi phí khác"]].map(([k,l])=><div className="field" key={k}><label>{l}</label><input type="number" value={x.costs?.[k]||""} onChange={e=>setc(k,e.target.value)}/></div>)}</div><div className="card" style={{marginBottom:10}}><div className="summary"><span>Tổng chi phí</span><b className="red">{money(cost)}</b></div><div className="summary"><span>Lợi nhuận</span><b className="green">{money(profit)}</b></div></div><button className="btn primary" onClick={save} disabled={saving}>{saving?"ĐANG LƯU...":x.id?"CẬP NHẬT":"LƯU CHUYẾN"}</button>{x.id&&<button className="btn danger" onClick={del}>XÓA CHUYẾN</button>}<button className="btn" style={{width:"100%",marginTop:9,background:"#eef2ef"}} onClick={onCancel}>HỦY</button></>
}
